### ISSUE TITLE
Tried running on robot car, no response

### ISSUE THREAD

**Issue by Cyberdr8gon** [sloughlin/STRATEGIC_WAR_SIMULATOR#1]
I don't understand why this doesn't work on my robot car. It uses a different camera, but it is still ros. I think you should fix this issue. K Thx Bye.

**Comment by sloughlin** [comment]
Did you remember to run source /opt/ros-version/setup.bash?

**Comment by Cyberdr8gon** [comment]
diD YoU rEmeMbER tO rUn SoUrcE /opt/ros-version/setup.bash?

**Comment by sloughlin** [comment]
Couldn't replicate, closing topic
